### PR TITLE
Creation of Animations for Naruto and Kyuubi Naruto

### PR DESCRIPTION
**Pull request by digitalbrilliancehour**
Acceptance Criteria:

Ensure that you can see all animations for both Naruto and kyuubiNaruto models in OpenBORStats. 

Naruto should be a player model, kyuubiNaruto should have a model type of “none”. 

Check against this animation list here:
https://github.com/digital-brilliance-hour/ogres-mayhem/wiki/Development-Move-List-for-character

### CODE REVIEW

**Comment by Capriangel** [comment]
Both Naruto and Kyuubi Naruto animation are good. You may merge this pull request.

**Comment by JingoBurch** [comment]
It looks like Naruto's punch is faster than his transformation punch

**Comment by JingoBurch** [comment]
You can now merge.

**Comment by digitalbrilliancehour** [comment]
Ok I'll go ahead and make sure that transformation punch is faster. Thanks @JingoBurch

**Pull request merged**
